### ISSUE TITLE
Add version to Docker image tag

### ISSUE THREAD

**Issue by miguelpmachado** [biotoolsdx/docker-htseq#1]
Hi @btrspg,
I was woundering if it would be possible to add the HTseq version to the TAG of your Docker image so it would be easier to identify correctly the Docker image.
Thanks very much.
Miguel

**Comment by btrspg** [comment]
@miguelpmachado Of course, thanks for the suggestion.

**Comment by btrspg** [comment]
@miguelpmachado Version tag has been added. Please see https://hub.docker.com/r/biotoolsdx/htseq/tags

**Comment by miguelpmachado** [comment]
Thanks
